[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "177eaf8f59f60d9367256a1abbee4a9cb08afb88"
os = "macos"

    [[Brplot.download]]
    sha256 = "29aba28ed25fe102c48cf313419fb232645dd2fcc9097285b245a43ed187b1ef"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.aarch64-apple-darwin.tar.gz"
[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "f7916e3b26cc6d8c5ee71d92f91337c77b6aa0b7"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "2e762c407a8c73c537d0ff1a169afe11f881aeaabdb1e107d6eb63b848a3d0e6"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.aarch64-linux-gnu.tar.gz"
[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "1a51e87d5ca29304d1c03498fbb90a2e5869d792"
os = "freebsd"

    [[Brplot.download]]
    sha256 = "6cf046b6fdba29aed315879ecb6c2e9c8fdfd7d72772bb15828bedbdaa186bd7"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.aarch64-unknown-freebsd.tar.gz"
[[Brplot]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c75da71bdb9d04f3c73e62429221b0b682020b4c"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "c070eb1a14001a15f547d106f00b45d40335cbac77ad27da7d90983d5ad25ae9"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.armv6l-linux-gnueabihf.tar.gz"
[[Brplot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6c06657328d244b29c949c3359e23769fb5f9284"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "d06a0be56b7b3fd6e5e2519b5dcd976c526aa4588f968a15d8388e922422bb60"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.armv7l-linux-gnueabihf.tar.gz"
[[Brplot]]
arch = "i686"
git-tree-sha1 = "43a9102c111ea06281dc23f9a62fb21d776851a6"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "e5e448bc3162175452f1175d82e3f9571a6ba6677e45605058e4f30d43661a1f"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.i686-linux-gnu.tar.gz"
[[Brplot]]
arch = "i686"
git-tree-sha1 = "250d440b5ad7412dee63a1c338e69746dbc29b92"
os = "windows"

    [[Brplot.download]]
    sha256 = "878a40b50d4d4887080b81fd071f2ec05014e80d7a2576cd1414898314d96f36"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.i686-w64-mingw32.tar.gz"
[[Brplot]]
arch = "powerpc64le"
git-tree-sha1 = "3bf9ac76d12c36ea3890ddb4761b91001e1821f0"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "756709aa433db89f9d66a9d9a0b3087c463ec37493ce9faadbe9be2d2107f806"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.powerpc64le-linux-gnu.tar.gz"
[[Brplot]]
arch = "riscv64"
git-tree-sha1 = "c797a04ab4fccc46892dfad1a88f00c351bb1bb6"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "82e8aad18b41db91c0029ab7753131f0854a40c2d542c264465d90ba237eeea1"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.riscv64-linux-gnu.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "15f1844c87810f97f4cb0af1fed323bffd42aa52"
os = "macos"

    [[Brplot.download]]
    sha256 = "ab69fccc96c5df87ecf2a1fada28f78e60d27dc3f79dd0dbf580094f7282649b"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.x86_64-apple-darwin.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "a7c6ebe5146c00a5a577dac702d669fe0a182420"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "4cc34ebd1d1d67bb9b4ad5f0094748666dd8f3b5a3edc38979e7e7efbc500929"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.x86_64-linux-gnu.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "19824a7d2705c9ddd6629f3c5fde1c480427f23e"
os = "freebsd"

    [[Brplot.download]]
    sha256 = "04f0993fc7d01c6fd7ddcc574819c4f0c863f4a64733984178b6c41d86b06b39"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.x86_64-unknown-freebsd.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "a3bc072cd0067757afbf8f5a0157a153e3f50cc9"
os = "windows"

    [[Brplot.download]]
    sha256 = "acdc3d53e02997cf36984010cb9e80a9348125ff7f781f07f79a9735b9cb9db2"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.5+0/Brplot.v0.0.5.x86_64-w64-mingw32.tar.gz"
