[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "772cfcda230ed3f47352c9c318dece7c53376cb9"
os = "macos"

    [[Brplot.download]]
    sha256 = "15c10277138ff067ba5230527f6dd5bbf09aae7489d9549a69d1bde897fc9bd0"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.aarch64-apple-darwin.tar.gz"
[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "bf5cd25c0faf7302c955df409ae923358d42d3b5"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "39f9497742bd70f8acac7fa1769407a2f5ef42f14e4defb959d12c74862401c9"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.aarch64-linux-gnu.tar.gz"
[[Brplot]]
arch = "aarch64"
git-tree-sha1 = "53b98e109bc85408fd2ad612aa5c6c604b7a4fa5"
os = "freebsd"

    [[Brplot.download]]
    sha256 = "049873ea04f7b07b58341b31419dae2ad4c1acc3d941b9d88089a4b099441c70"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.aarch64-unknown-freebsd.tar.gz"
[[Brplot]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "63ee0e9b8f8b5b71b8c0a94238b17c7351da916e"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "fc9b239e97c5c6b158c2ffdec670dafc0a9bb00aebbef2a7ef8ef97d46fbd202"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.armv6l-linux-gnueabihf.tar.gz"
[[Brplot]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ac095881c7153e16d1bc1b2bfdfd4eea06ff4491"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "55efe5c44d9fe28ed8295c5029764602c1ffa790de57bdf58685fd736da6e66d"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.armv7l-linux-gnueabihf.tar.gz"
[[Brplot]]
arch = "powerpc64le"
git-tree-sha1 = "d6cf3d1af0e5836dec17620be84a1ec6165a3c77"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "b47af51b35ab5beea129e276b614d210c60b4030f4437795d36addda63641732"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.powerpc64le-linux-gnu.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "3295e7942f925b40d7acf30c94f8f380f91670bc"
os = "macos"

    [[Brplot.download]]
    sha256 = "dda9fe826226f0d9cba2b6d3718ffadc73c1952efbf683aa93f95e8cf4f5b063"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.x86_64-apple-darwin.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "7c64c51bd063e044bfd507e31271dabde05e11d6"
libc = "glibc"
os = "linux"

    [[Brplot.download]]
    sha256 = "2f9eb3f2228acac8681916cc0dd9f8682587568c57b0e9f9c617f5e96a59e0b7"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.x86_64-linux-gnu.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "5fc9d5041b632ab8369cea6754fbef99c9b2641f"
os = "freebsd"

    [[Brplot.download]]
    sha256 = "80ccdc56ee3bb32191123c0a6e1f1ec4898738240b10b8855affc44413c6efcf"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.x86_64-unknown-freebsd.tar.gz"
[[Brplot]]
arch = "x86_64"
git-tree-sha1 = "2dbf5487a8273c727bab2050088ae5af69e60c8a"
os = "windows"

    [[Brplot.download]]
    sha256 = "c8048b7974db22ad25cff2a85c0273410e3b47c06be07aece1f780fde3dde547"
    url = "https://github.com/brplot/Brplot_jll/releases/download/Brplot-v0.0.4+0/Brplot.v0.0.4.x86_64-w64-mingw32.tar.gz"
