# Autogenerated wrapper script for Brplot_jll for i686-w64-mingw32
export libbrplot

JLLWrappers.@generate_wrapper_header("Brplot")
JLLWrappers.@declare_library_product(libbrplot, "libbrplot.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbrplot,
        "bin\\libbrplot.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
