# Autogenerated wrapper script for Brplot_jll for riscv64-linux-gnu
export libbrplot

JLLWrappers.@generate_wrapper_header("Brplot")
JLLWrappers.@declare_library_product(libbrplot, "libbrplot.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbrplot,
        "lib/libbrplot.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
