# Autogenerated wrapper script for Brplot_jll for x86_64-apple-darwin
export libbrplot

JLLWrappers.@generate_wrapper_header("Brplot")
JLLWrappers.@declare_library_product(libbrplot, "@rpath/libbrplot.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libbrplot,
        "lib/libbrplot.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
